replicaCount: 1
logLevel: debug
insecureTls: false
image:
  repository: quay.io/coreos/clair
  tag: v2.1.6
  pullPolicy: IfNotPresent
service:
  name: clair
  type: ClusterIP
  internalApiPort: 6060
  externalApiPort: 6060
  internalHealthPort: 6061
  externalHealthPort: 6061
resources:
  limits:
    cpu: 2
    memory: 3000Mi
  requests:
    cpu: 50m
    memory: 2000Mi
config:
  postgresURI: "postgres://user:password@host:5432/postgres"
  updateInterval: 2h
  enabledUpdaters:
  - debian
  - ubuntu
  - rhel
  - oracle
  - alpine
  enabledNamespaceDetectors:
  - os-release
  - lsb-release
  - apt-sources
  - alpine-release
  - redhat-release
  enabledFeatureListers:
  - apk
  - dpkg
  - rpm
postgresql:
# The dependant Postgres chart can be disabled, to connect to
# an existing database by defining config.postgresURI
  enabled: true
  image:
    debug: true
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      cpu: 2
      memory: 512Mi
  postgresqlUsername: postgres
  postgresqlPassword: clair
  persistence:
    size: 1Gi
  networkPolicy:
    enabled: true
