# Default values for clair.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: francoisminaud/grafana-pdf-export
  tag: v1.3
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 50m
    memory: 500Mi
config:
  uploadToAWS:
    enabled: false
  secretEnvVars:
    AWS_ACCESS_KEY_ID: SETME
    AWS_SECRET_ACCESS_KEY: SETME
    AWS_BUCKET_NAME: SETME
    GRAFANA_USER: SETME
    GRAFANA_PASSWORD: SETME
