# Default values for clair.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: francoisminaud/grafana-pdf-export 
  tag: v1.0
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 50m
    memory: 500Mi
config:
  secretEnvVars:
    AWS_ACCESS_KEY_ID:  ""
    AWS_SECRET_ACCESS_KEY: ""
    AWS_REGION: ""
    AWS_BUCKET_NAME: ""
    GRAFANA_USER: ""
    GRAFANA_PASSWORD: ""
  
