apiVersion: v2
name: keycloak-operator
version: 0.0.3
appVersion: "17.0.0"
description: Helm chart for deploying keycloak operator
keywords:
  - keycloak
  - operator
sources:
  - https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/keycloak-operator
  - https://github.com/keycloak/keycloak-operator
engine: gotpl
icon: https://www.keycloak.org/resources/images/keycloak_icon_512px.svg
maintainers:
- name: desaintmartin
  email: cdesaintmartin@wiremind.io
- name: machine424
  email: amrini@wiremind.io
- name: francoisminaud
  email: fminaud@wiremind.io
- name: maxime1907
  email: 19607336+maxime1907@users.noreply.github.com
