annotations:
  category: DeveloperTools
apiVersion: v2
name: keycloak-operator-crds
version: 0.0.11-labels0
appVersion: "17.0.0"
description: Manage keycloak-operator CRDs
keywords:
  - keycloak
  - operator
  - crds
sources:
  - https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/keycloak-operator-crds
  - https://github.com/keycloak/keycloak-operator
engine: gotpl
icon: https://www.keycloak.org/resources/images/keycloak_icon_512px.svg
maintainers:
- name: desaintmartin
  email: cdesaintmartin@wiremind.io
- name: machine424
  email: amrini@wiremind.io
- name: francoisminaud
  email: fminaud@wiremind.io
- name: maxime1907
  email: 19607336+maxime1907@users.noreply.github.com
