apiVersion: v2
appVersion: "1.0"
description: pghoard
name: pghoard
version: 0.8.1
maintainers:
- name: desaintmartin
  email: cdesaintmartin@wiremind.io
- name: machine424
  email: amrini@wiremind.io
