annotations:
  category: DeveloperTools
apiVersion: v2
name: topolvm-crds
version: 4.0.1
appVersion: 0.10.5
description: Manage topolvm CRDs
keywords:
  - topolvm
  - crds
sources:
  - https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/topolvm-crds
  - https://github.com/topolvm/topolvm/tree/main/charts/topolvm
engine: gotpl
icon: https://i.imgur.com/iqSQEf7.png
maintainers:
- name: desaintmartin
  email: cdesaintmartin@wiremind.io
- name: machine424
  email: amrini@wiremind.io
- name: francoisminaud
  email: fminaud@wiremind.io
- name: maxime1907
  email: 19607336+maxime1907@users.noreply.github.com
